### PR TITLE
Revert #225 to make Windows+SDL builds use the SDL device again

### LINKED ISSUE #239: Windows/SDL CI builds fail
Fails since merging #210... apparently that was the reason for it being WIP, there was no Windows/SDL CI when I opened it.

MinGW builds fail like:
```/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/IrrlichtMt.dir/objects.a(MaterialRenderer.cpp.obj):MaterialRenderer.cpp:(.text+0x193d): undefined reference to `__imp_glCompileShader'```

while MSVC builds do like:
```2023-09-18T21:27:33.4491337Z D:\a\irrlicht\irrlicht\source\Irrlicht\OpenGL\ExtensionHandler.cpp(42,33): error C2382: 'irr::video::COpenGL3ExtensionHandler::queryExtension': redefinition; different exception specifications [D:\a\irrlicht\irrlicht\source\Irrlicht\IRRVIDEOOBJ.vcxproj]```

### LINKED ISSUE #246: Windows+SDL broken by #225
@nerzhul

#225 removed `IRR_COMPILE_WITH_WINDOWS_DEVICE`. Windows builds now always include the Windows Irrlicht device. However, SDL builds must only contain the SDL Irrlicht device. If both the Windows device and the SDL device exist, the Windows device takes precedence:

https://github.com/minetest/irrlicht/blob/9954667c45cc6c184ead60b516e532111556e56a/source/Irrlicht/Irrlicht.cpp#L58-L97

As a result, `USE_SDL2` has no effect anymore on Windows. I suggest reverting #225 for now to make these builds work again, the PR can always be redone correctly later.

## How to reproduce

Compile Minetest with `-DUSE_SDL2=TRUE` on Windows. See that the "About" tab still shows "Irrlicht device: WIN32".

---

This doesn't seem to be the same issue as #239, the CI still fails after reverting #225.

### PR DESCRIPTION
**Pull request by grorp**
Fixes #246. (Doesn't have an effect on #239.)

This PR reverts #225 to make Windows+SDL builds use the SDL device again. Currently, they contain both the Windows device and the SDL device, but they always use the Windows device.

This PR is only intended as a temporary fix until #225 is redone correctly.

## How to test

Compile Minetest with `-DUSE_SDL2=TRUE` on Windows. Verify that the "About" tab shows "Irrlicht device: SDL".

### CODE REVIEW

**Comment by numberZero** [comment]
https://github.com/minetest/irrlicht/blob/9954667c45cc6c184ead60b516e532111556e56a/source/Irrlicht/CMakeLists.txt#L375
Wouldn’t just replacing `WIN32` with `DEVICE STREQUAL "WINDOWS"` be enough?
