### ISSUE TITLE
Windows/SDL CI builds fail

### ISSUE THREAD

**Issue by numberZero** [minetest/irrlicht#239]
Fails since merging #210... apparently that was the reason for it being WIP, there was no Windows/SDL CI when I opened it.

MinGW builds fail like:
```/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/IrrlichtMt.dir/objects.a(MaterialRenderer.cpp.obj):MaterialRenderer.cpp:(.text+0x193d): undefined reference to `__imp_glCompileShader'```

while MSVC builds do like:
```2023-09-18T21:27:33.4491337Z D:\a\irrlicht\irrlicht\source\Irrlicht\OpenGL\ExtensionHandler.cpp(42,33): error C2382: 'irr::video::COpenGL3ExtensionHandler::queryExtension': redefinition; different exception specifications [D:\a\irrlicht\irrlicht\source\Irrlicht\IRRVIDEOOBJ.vcxproj]```
